"""
Export realistic test pairs for evaluation from jobs and resumes in MongoDB.
Pairs are generated by matching resumes to jobs with keyword overlap and skills alignment.
"""

import os
from pathlib import Path
import random
import json
from load_data import load_jobs_from_db, load_resumes_from_db

def generate_realistic_test_pairs(num_pairs=100, output_path="data/test_pairs.json"):
    jobs = load_jobs_from_db(limit=500)
    resumes = load_resumes_from_db(limit=100)
    if not jobs or not resumes:
        print("Error: Need jobs and resumes in database to generate test pairs")
        return

    pairs = []
    for _ in range(num_pairs):
        resume = random.choice(resumes)
        job = random.choice(jobs)
        resume_text = resume.get('content', '').lower()
        job_text = f"{job.get('job_title', '')} {job.get('description', '')}".lower()
        # Heuristic: overlap and skills
        resume_words = set(resume_text.split())
        job_words = set(job_text.split())
        overlap = len(resume_words & job_words)
        score = min(overlap / 50.0, 1.0)
        is_match = score > 0.3
        relevance_score = round(score, 2)
        pairs.append({
            "resume": resume_text[:500],
            "job": job_text[:500],
            "is_match": is_match,
            "relevance_score": relevance_score
        })

    output_dir = Path(output_path).parent
    output_dir.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(pairs, f, indent=2, ensure_ascii=False)
    print(f"Exported {len(pairs)} test pairs to: {output_path}")

if __name__ == "__main__":
    generate_realistic_test_pairs()
